CrowdStrike/monorepo-next

- src/build-dag.js
- test/build-dag-test.js
> fix: retain empty version strings in `buildDAG`

- src/version.js
- test/version-test.js
Resolves #114, allowing wirdcard versions -- useful for denoting "always latest" dependencies in a monorepo
> feat(#114): support wildcard versions

- test/attach-test.js
- test/detach-test.js
- test/release-test.js
"fixturify.readSync no longer supports options.exclude, please use options.ignore instead."
> chore: remove `fixturify.readSync` deprecation notice

- src/changed-files.js
- test/changed-files-test.js
BREAKING CHANGE: `ext` string is now `exts` array of strings
> feat: allow multiple extensions at once

- src/build-change-graph.js
Discovered here https://github.com/CrowdStrike/monorepo-next/pull/136/files#r498824657
> fix: remove unused `sinceBranch` arg

- src/get-changelog.js
- test/get-changelog-test.js
This will allow you to create changelogs of arbitrary commits, instead of based on releases.
> feat: support `fromCommit` in `getChangelog`

- src/build-change-graph.js
- src/get-latest-release-commit.js
- src/git.js
- src/index.js
- test/get-latest-release-commit-test.js
For convenience to be used externally.
> feat: expose `getLatestReleaseCommit`

- src/build-dep-graph.js
- src/get-changelog.js
Since require caches and the versions could change, we could be reading the wrong values.
> fix: never use `require` to load `package.json`

- package.json
- yarn.lock
Either they break semver multiple times in 7.x range, or we are using non-public API that keeps changing.
> fix: pin semver package

- package.json
- src/build-change-graph.js
- src/build-dep-graph.js
- test/build-change-graph-test.js
- test/build-dep-graph-test.js
- test/build-release-graph-test.js
- test/release-test.js
The child package exclusion from monorepo root logic only considered the current release. Old package changes would still show up for the monorepo root on future releases because the root tag stayed in pre-release location.
> fix: ignores old child package changes in root package

- package.json
- yarn.lock
This was causing explosive recursion in node_modules and yarn cache. Probably a yarn bug.
> chore: remove file link

- test/build-change-graph-test.js
- test/changed-files-test.js
- test/changed-test.js
- test/run-test.js
These could cause confusion that they are actually used when they are not.
> chore: remove unnecessary version hints from tests

- bin/commands/changed-files.js
- bin/commands/changed.js
- bin/commands/run.js
- bin/common-args.js
- src/build-change-graph.js
- src/changed-files.js
- src/changed.js
- src/run.js
so functions like `changed` and `changedFiles` can exclude them
> add a way to opt-in to excluding all npm ignored changes

- bin/commands/changed-files.js
- bin/commands/changed.js
- src/changed-files.js
- src/changed.js
These are too noisy. Let's move the logging to the command.
BREAKING CHANGE: the `silent` option is removed from the js functions, and the js functions no longer log to console.
> fix: remove logging of js `changed` and `changedFiles`

- src/build-change-graph.js
- src/changed-files.js
- src/changed.js
- test/build-change-graph-test.js
This is similar to `fromCommit`, but does the heavy lifting to ignore the commit if it is older than the last version commit.
> feat: add `fromCommitIfNewer`

- src/build-change-graph.js
- src/releasable.js
- test/build-change-graph-test.js
- test/releasable-test.js
This causes problems when trying to create temp files when trying to calculate releasability.
> fix: strip dirs from git status

- src/changed-files.js
- test/changed-files-test.js
- Utility function to check for generic changes files
- Might be useful for checking on changes per file type
- Similar API to `changedFiles` but needs `matchers` object to assign matched files to respective group:
```js
matchers: {
'files': /.txt/,
'configs': /.my-config.json/,
},
```
produces (assuming given files have been changed):
```js
{
files: ['foo.txt', 'package-a/bar.txt'],
configs: ['.my-config.json', 'package-b/.my-config.json']
}
```
-----
Also I think it should be possible to replace `changedFiles` implementation with something like:
```js
let matchers = exts.map(
(ext) => {
return { 
ext: new RegExp('\.' + ext)
}
}
);
return changedStuff({
matchers,
...arguments
}).values().flat();
```
Obviously a little bit overkill.
> feat: new utility function for getting a list of changed files grouped

- src/changed-files.js
- src/changed.js
- test/changed-test.js
I have made changes to return package names instead of base names for all the apps changed.
When there are multiple apps with same basenames(in different paths), change detection matches all those apps even though only one is changed
This change only affects changed and nothing else.
> feat!: fix changed, matching all apps with same basename

- src/build-change-graph.js
- src/changed-files.js
- src/changed.js
- test/build-change-graph-test.js
- test/changed-files-test.js
- test/changed-test.js
We want to be able to calculate any commit without having to checkout the commit first.
> feat: expose toCommit in `changed` and `changedFiles`

- src/attach.js
- src/build-change-graph.js
- src/build-dag.js
- src/build-release-graph.js
- src/changed-files.js
- src/changed.js
- src/detach.js
- src/get-changelog.js
- src/release.js
- src/run.js
- test/build-change-graph-test.js
- test/build-dag-test.js
- test/build-release-graph-test.js
Using a lookup table for visited packages can speed this up a lot.
> feat: short-circuit buildDAG

- src/build-release-graph.js
- src/release.js
- test/build-release-graph-test.js
> refactor: convert releaseTrees dependencies to object

- src/build-release-graph.js
These don't re-enter like the other crawlDag calls, so it's safe to cache. This should be temporary. A more permanent solution like combining all the passes may be better.
> feat: early exit some crawlDag calls

- src/build-dep-graph.js
- src/get-workspaces-paths.js
**Summary**
add getWorkspacesPaths to monorepo-next. This will return workspaces in a monorepo and will work with pnpm and yarn workspaces
Test Plan:
1. verify getWorkspacesPaths return correct values from monorepo
2.  tests pass
135 passing
> add getWorkspacesPaths to monorepo-next

- package.json
- src/get-workspaces-paths.js
- test/attach-test.js
- test/build-change-graph-test.js
- test/detach-test.js
- test/fixtures/workspace/package.json
- test/release-test.js
- yarn.lock
Summary
Instead of glob use `yarn workspaces list` to return workspaces. This is more accurate than globs
Test Plan
All tests are passing but some are timing out with default timeout
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
> refactor yarn spawn

- commitlint.config.js
- src/changed-files.js
- test/changed-files-test.js
If you structure your packages like "*/package", you will have lots of packages with the same basename, so we can't use this to scope changes to a package.
BREAKING CHANGE: This fix means everyone using `changedFiles.packages` needs to update to a full relative path instead of just the basename. For example, a package at "packages/my-package" will go from:
```js
changedFiles({
packages: ['my-package'],
})
```
to
```js
changedFiles({
packages: ['packages/my-package'],
})
```
> fix: support packages with same basename

- src/releasable.js
- test/releasable-test.js
If you remove a whole package, the package's removed files show up as belonging to the monorepo root package. The package's package.json gets read in our temporary dir by packlist because the root package.json still matches the package. This prevents a malformed JSON error.
> accommodate removed package jsons

- src/releasable.js
If you have a massive amount of removed files, I think it was the `path.relative` that was slow. Doing it this way is both simpler and faster.
> fix: speed up `removeSubDirs`

- src/config.js
- test/build-change-graph-test.js
Add support for CJS config file extension.
This will allow to use `monorepo-next.config.cjs` file, and will take precedence over `.js` (which can be implicitly ESM)
> feat: Add support for CJS config file extension 

- src/cycle.js
- test/cycle-test.js
If packages are not alphabetized, or are rearranged in a monorepo, they can result in a different order of cycles, based on which node is chosen to start the loop. This forced sorting should solve that.
> fix: always sort Object.keys to be deterministic

- test/changed-test.js
If you have 'main' set locally as default, these tests fail.
> chore: fix tests to run with default branch

- package.json
- yarn.lock
They have been known to break semver, ironically, but I'm tired of bumping this package.
> fix: float semver package version range

- src/build-release-graph.js
This means we haven't processed it yet, and it will be encountered on another loop because it must have changes itself.
> fix: early exit if child is of greater release type

- src/build-change-graph.js
- test/build-change-graph-test.js
if filename has space like `sample index.js`, if its modified and uncommited, that file will have double quotes in git status
example: '"packages/package-a/sample index.js"'. We need to strip `"` for that reason
> fix: handle filenames with spaces

- src/get-changelog.js
- test/get-changelog-test.js
changelog is truncating repository url `///compare/@scope/my-app@1.0.0...@scope/my-app@1.0.1`. We didn't catch this issue when `conventional-changelog` updated to `5.1.0` because none of the tests are configured with repository block in package.json.
> fix: fix changelog truncating repository url

- src/build-change-graph.js
I had a feeling it took more time to spawn git in a loop than the benefit you get by getting a git diff per-package, especially when you are using a `fromCommit` instead of version tags.
In a test of mine, this brought `buildChangeGraph` down to 25 seconds from 39 seconds.
> feat: add shouldRunPerPackage option

- bin/commands/release.js
- src/build-release-graph.js
- src/get-changelog.js
- src/get-new-versions.js
- src/release.js
- test/build-release-graph-test.js
This prevents publishing a package that depends on a private package.
> feat: add shouldValidateDependencyVisibility option

- src/version.js
- test/version-test.js
Initial versioning can ruin your version hint. For example, from ^0.0.0 to ~1.0.0. This fixes it to be from ^0.0.0 to ^1.0.0.
> feat: use existing range if available

- src/fs.js
- src/release.js
- test/release-test.js
Unlike other package managers, pnpm stores the package.json version in the lockfile as well. We need to update that during release as well.
> feat: support updating pnpm lockfile

- README.md
- src/build-change-graph.js
- src/releasable.js
- test/releasable-test.js
Packages that have a build step don't get tracked during the release process. Because their `files` array has something like `dist`, it doesn't track any files in git, and it looks like it doesn't have any releasable changes. This option appends your existing NPM settings, so you don't have to duplicate a long files list.
> feat: add `changeTrackingFiles` option to monorepo-next.config.js

- src/version.js
- test/version-test.js
This reverts commit 16c93e921e7fc09c735b0edb14456318a1e070b2, reversing changes made to 36b3e7aac0f95408439de509f3b0ad2974aaff94.
I'm going to reapply this as a more complete fix.
> Revert "Merge pull request #527 from kellyselden/trackNewVersion"

- src/build-dag.js
- test/build-dag-test.js
The bug stopped at the first level. It assumed private packages are only devDependencies, but if your monorepo is all private packages, including dependencies, you will break the tree if only going one layer deep.
> fix: follow private dependents all the way down
