CrowdStrike/monorepo-next

src/release.js
tags have to be annotated for `--follow-tags` to work.
https://stackoverflow.com/a/56546026/1703845
=> fix: create annotated tag

src/build-dag.js, src/build-release-graph.js, test/build-dag-test.js, test/build-release-graph-test.js
=> fix: track newly out of range

src/build-release-graph.js, src/dependency-types.js, test/build-dag-test.js, test/build-release-graph-test.js, test/fixtures/workspace/packages/package-c/package.json
=> fix: treat `optionalDependencies` like other dependency types

src/get-changelog.js, test/get-changelog-test.js
=> feat: allow generating changelog for multiple versions

src/get-changelog.js, test/get-changelog-test.js
`TypeError: Cannot read property 'releaseType' of undefined`
=> chore: add failing test for generating changelog when only dep changed

src/build-change-graph.js, src/git.js, test/build-change-graph-test.js, test/release-test.js
=> support new packages without an existing version tag

src/build-dep-graph.js, test/build-dep-graph-test.js
=> fix: ignore empty package dirs

.travis.yml, config/ember-cli-update.json, package.json
BREAKING CHANGE: bump min node to 10
=> chore: track `standard-node-template`

src/get-new-versions.js, src/index.js, test/get-new-versions-test.js
It's like a dry run release in object form.
=> feat: create `getNewVersions` public api

src/get-changelog.js, test/get-changelog-test.js
This makes a revert changelog section make more sense.
=> feat: don't increment changelog version if going backwards

package.json, yarn.lock
This is the next limit before another breaking change happens.
=> fix: update semver to 7.3.2

package.json, src/version.js, yarn.lock
Coming from https://github.com/npm/node-semver/pull/324.
=> fix: fix change in semver package

src/get-new-versions.js, test/get-new-versions-test.js
BREAKING CHANGE: The object structure has changed.
=> feat: expose old version and release type in `getNewVersions`

.mocharc.js, test/run-test.js
This cuts the test times in half (1m => 30s).
=> chore: run mocha in parallel

src/build-release-graph.js, test/build-release-graph-test.js, test/release-test.js
`buildChangeGraph` already had this benefit. It was missing from `buildReleaseGraph`.
=> fix: don't version bump if dev dep changes

bin/commands/changed-files.js, bin/commands/changed.js, bin/commands/release.js, bin/commands/run.js, bin/common-args.js, package.json, src/build-change-graph.js, src/build-release-graph.js, src/changed-files.js, src/changed.js, src/get-changelog.js, src/get-new-versions.js, src/git.js, src/releasable.js, src/release.js, src/run.js, test/build-change-graph-test.js, test/build-release-graph-test.js, test/releasable-test.js, test/release-test.js, yarn.lock
=> exclude devDependency changes from releasability

src/build-release-graph.js, test/build-release-graph-test.js
This happens anyways, we can just short circuit for slow repos.
=> fix: assume patch level as default

package.json, src/debug.js, src/git.js, yarn.lock
use via `DEBUG=monorepo-next:git ...`
=> feat: add debug logging to git

bin/commands/release.js, src/release.js, test/release-test.js
This is to prevent accidentaly release when you are using something like "main" as your default branch.
=> feat: add release `--default-branch` option

src/build-release-graph.js
Reverts CrowdStrike/monorepo-next#312
=> Revert "feat: early exit some crawlDag calls"

README.md, src/build-change-graph.js, src/build-release-graph.js, src/config.js, test/build-change-graph-test.js, test/build-release-graph-test.js
=> feat: add support for `monorepo-next.config.js`

src/build-dep-graph.js, src/get-workspaces-paths.js, src/json.js
**Summary**
1. Add option to return workspaces synchronous in get-workspaces-paths.js
**Test Plan**
All tests are passing
I will add new test
=> Get workspaces synchronous

src/releasable.js, test/releasable-test.js
Closes #318. cc @NullVoxPopuli @sbonasu
=> handle a dir of files converted to a single file where the dir was

.github/workflows/ci.yml, package.json, src/build-dep-graph.js, src/get-workspaces-paths.js, test/get-workspaces-paths-test.js, yarn.lock
I also updated workspaceCwd to cwd since workspace is already implied by the function name.
=> refactor: refactor and add tests for `getWorkspacesPaths`

package.json, src/get-workspaces-paths.js, test/changed-files-test.js, test/get-workspaces-paths-test.js, yarn.lock
=> Get workspaces paths refactors

src/get-workspaces-paths.js, test/get-workspaces-paths-test.js
README.md file path is being returned as packagePath which is a file not directory
=> fix ENOTDIR error

bin/commands/cycles.js, src/cycle.js, src/detect-circular-references.js, test/cycle-test.js, test/detect-circular-references-test.js
This can detect circular references.
=> feat: add cycles command

test/build-change-graph-test.js, test/changed-files-test.js, test/release-test.js
If you have 'main' set locally as default, these tests fail.
=> chore: fix tests to run with default branch

src/release.js
You can end up swallowing the error.
=> fix: don't try to clean up during dry run

src/build-release-graph.js, src/log.js, src/release.js
It wasn't handling synchronous functions correctly.
=> fix: fix logger

.github/workflows/ci.yml
=> chore: bump pnpm to v8

package.json, src/fs.js, src/git.js, test/git-test.js, yarn.lock
This allows multiple processes to share the cache.
=> feat: cache git results in files

package.json, yarn.lock
includes https://github.com/absolute-version/commit-and-tag-version/pull/23
=> chore!: "commit-and-tag-version": "11.0.0"
